# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}', '.']

    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 
             'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}' ]

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args: ['run', 'deploy', '${_SERVICE_NAME}',
       '--platform', 'managed', '--region', '${_REGION}',
       '--allow-unauthenticated',
       '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}']

    # Force the new revision to serve 100% of traffic.
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gcloud'
      args: ['run', 'services', 'update-traffic', '${_SERVICE_NAME}', '--to-latest',
       '--platform', 'managed', '--region', '${_REGION}']

    # Cleanup tags against closed pull requests
    - name: 'gcr.io/${PROJECT_ID}/deployment-previews'
      args: ['cleanup',
             '--project-id', '${PROJECT_ID}',
             '--region', '${_REGION}',
             '--service', '${_SERVICE_NAME}',
             '--repo-name', '${_GITHUB_USER}/${REPO_NAME}',
             '--tag-file', "${_TAG_FILE}"]
    
    # FIX(glasnt) For tags identified, remove them
    # requires a local file: delete-tags.sh
    # 
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: '/bin/sh'
      args: ['./delete-tags.sh', "${SERVICE}", "${REGION}", "${_TAG_FILE}"]

substitutions:
    _SERVICE_NAME: myservice
    _REGION: us-central1
    _TAG_FILE: tags-to-delete.txt
